" encoding
scriptencoding utf-8
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-boms,utf-8,euc-jp,cp932
set fileformats=unix,dos,mac
set ambiwidth=single

if exists('g:vscode')
    " must have nvim
    let s:setting_dir= "$HOME/.config/nvim/config/"
    exec 'source ' . s:setting_dir . 'vscode_conf.vim'
elseif has('nvim')
    let s:setting_dir= "$HOME/.config/nvim/config/"
    exec 'source ' . s:setting_dir .'deinconf.vim'
    exec 'source ' . s:setting_dir .'default.vim'
else
    " if cannot use nvim
    if &compatible
        set nocompatible               " Be improved
    endif
    let s:setting_dir = "$HOME/.vim/config/"
endif


" depend on language
augroup fileTypeIndent
    autocmd!
    autocmd BufNewFile,BufRead *.py setlocal tabstop=2 softtabstop=2 shiftwidth=2
    autocmd BufNewFile,BufRead *.rb setlocal tabstop=2 softtabstop=2 shiftwidth=2
augroup END

if executable('im-select')
    autocmd InsertLeave * :call system('im-select com.apple.keylayout.ABC')
    autocmd CmdlineLeave * :call system('im-select com.apple.keylayout.ABC')
endif
